#!/bin/bash

# redirect stderr
exec 2>&1

# activate the virtual environment
source {{pkg.svc_data_path}}/{{pkg.name}}/flappy_env/bin/activate

# run the flask app
exec gunicorn -b 127.0.0.1:9001 --chdir {{pkg.svc_data_path}}/{{pkg.name}} is_flappy:app -w 4

