#!/usr/bin/env python3

import argparse
import logging
import socket
import sys

parser = argparse.ArgumentParser()
parser.add_argument("port", help="port to check", type=int)
args = parser.parse_args()


def tcp_check(host, port):
    count = 0
    for i in range(5):
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            result = s.connect_ex((host, port))
            s.close()
            if result == 0:
                count += 1
        except socket.gaierror:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            result = s.connect_ex((host.strip(), port))
            s.close()
            if result == 0:
                count += 1
    return count


for host in sys.stdin:
    successful_check = tcp_check(host, args.port)
    if successful_check == 5:
        print(
            "service using port {} on host {} is reporting ok".format(
                args.port, host.strip()
            )
        )
    elif successful_check == 0:
        print(
            "service using port {} on host {} is NOT REPORTING".format(
                args.port, host.strip()
            )
        )
    else:
        print(
            "service using port {} on host {} is flappy".format(args.port, host.strip)
        )
